plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
//    id 'com.didi.dokit'
    id 'io.realm.kotlin'
    id 'com.google.dagger.hilt.android'
    id 'com.google.devtools.ksp'
}

apply plugin: "class-res-guard"
apply plugin: "xml-class-guard"

apply from: 'classResGuard.gradle'
apply from: 'xmlClassGuard.gradle'

ksp { arg("AROUTER_MODULE_NAME", project.getName()) }

android {
    namespace "com.wan.android"
    compileSdk 35


    defaultConfig {
        applicationId "com.wan.android"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"

        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        dataBinding true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

//    //DoKit
//    debugImplementation "io.github.didi.dokit:dokitx:3.5.0"
//    releaseImplementation "io.github.didi.dokit:dokitx-no-op:3.5.0"

    //leakcanary
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.9.1'

    //使用ARouter的模块都要配置
//    kapt 'com.alibaba:arouter-compiler:1.5.2'
    ksp 'com.github.JailedBird:ArouterKspCompiler:1.9.20-1.0.7'

    //login模块
    implementation project(path: ':login')

    //hilt
    def hilt_version = '2.51.1'
    implementation "com.google.dagger:hilt-android:$hilt_version"
    ksp "com.google.dagger:hilt-compiler:$hilt_version"

}